### ISSUE TITLE
Bitcoin mining 

### ISSUE THREAD

**Issue by khudhon** [wso2/wso2-wss4j#97]
**Description:**

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by khudhon** [comment]
Bitcoin mining

**Comment by khudhon** [comment]
How to cash bitcoin mining

**Comment by anupama-pathirage** [comment]
Invalid issue
